name: irgan 
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.6
  - click=6.7
  - pandas=1.0.3
  - cudatoolkit=9.0
  - h5py=2.8.0
  - opencv=3.4.1
  - scikit-learn=0.19.1
  - tqdm=4.24.0
  - pyyaml=5.1
  - pytorch=0.4.1
  - torchvision=0.2.1
  - pip:
    - visdom==0.1.8.5
    - tensorboardx==2.0
